# src/main/resources/application.properties
# ????????? ??????????? ? ?????????? ?? H2
db.url=jdbc:h2:file:./social_network.db
db.driver=org.h2.Driver
db.user=sa
db.pass=

# ????????? Hibernate
jpa.hibernate.ddl-auto=update
jpa.show-sql=false
jpa.format-sql=false
jpa.dialect=org.hibernate.dialect.H2Dialect